### ISSUE TITLE
missing TileMatrixSet in TileMatrix

### ISSUE THREAD

**Issue by webstep-or** [mylen/leaflet.TileLayer.WMTS#8]
example with tilematrix 8 and TileMatrixSet EPSG:32633
should be TileMatrix=EPSG:32633:8 
not TileMatrix=8

**Comment by pfeely** [comment]
I had the same issue - a quick fix was to change the url to use the tilematrixset paramater and append the zoom level, then remove the tilematrix paramter

var params = L.Util.getParamString(this.wmtsParams, url) + "&tilematrix="+this.wmtsParams.tilematrixset+":" + zoom + "&tilerow=" + tilerow +"&tilecol=" + tilecol ;
        return url + params;



eg:

var vicmap = L.tileLayer.wmts('https://api.maps.vic.gov.au/geowebcacheWM/service/wmts?', {
    	layer:	"SATELLITE_WM",    	
    	format: "image/png",
    	tilematrixset: "EPSG:3857_SATELLITE_WM",
    	tileSize: 512,
        maxZoom : 19,
        minZoom: 6
    });

**Comment by jordanparfitt** [comment]
I updated line 54 to this: seems to have worked

`
        return url + L.Util.getParamString(this.wmtsParams, url) + "&tilematrix=" + this.wmtsParams.tilematrixSet + ":" + ident + "&tilerow=" + tilerow +"&tilecol=" + tilecol;`

**Comment by mylen** [comment]
thank you
